In [159]:
#grafo = np.array([[0, 10, 15, 20], [10, 0, 35, 25], [15, 35, 0, 30], [20, 25, 30, 0]]) #Matriz Simétrica
grafo = np.array([[0, 5, 8, 3], [5, 0, 7, 6], [8, 7, 0, 4], [3, 6, 4, 0]]) #Exemplo do Excel
#grafo = retornaMatrizSimestricaAleatoria(10)
print (grafo)
v=grafo.shape[1]
s = 0
inicio = timeit.default_timer()

res = fb(grafo, s); #Chamada da Função - Força Bruta
#res=vizproximo(grafo,s)

fim = timeit.default_timer()
print ('Tempo de Execução: %f' % (fim - inicio), ' segundos.')

print("Menor Caminho: ",res)

[[0 5 8 3]
 [5 0 7 6]
 [8 7 0 4]
 [3 6 4 0]]
0  - Solucao testada: x=   [0, [1, 2, 3], 0] f(x)=  19
1  - Solucao testada: x=   [0, [1, 3, 2], 0] f(x)=  23
2  - Solucao testada: x=   [0, [2, 1, 3], 0] f(x)=  24
3  - Solucao testada: x=   [0, [2, 3, 1], 0] f(x)=  23
4  - Solucao testada: x=   [0, [3, 1, 2], 0] f(x)=  24
5  - Solucao testada: x=   [0, [3, 2, 1], 0] f(x)=  19
Tempo de Execução: 0.006732  segundos.
Menor Caminho:  [19, array([0, list([1, 2, 3]), 0], dtype=object), 6]


<ipython-input-156-7c8a2de680e1>:33: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  solucao=np.array([0,vertex2,0])


In [2]:
#bloco de definição de variáveis e funções (Força Bruta e vizinho mais próximo)

import numpy as np
import time
import timeit
import random
from datetime import datetime

#bloco de definição de variáveis e funções


def fb(grafo, s):
    vertex = []
    vertex2 = []
    for i in range(v): #Gera vetor dos vértices
        if i != s:
            vertex.append(i)
        
    custo_min = 999999999
    iter = 0
    vertex2=vertex.copy()
    solucao = [0,vertex,0]
    while True:

        custo_atual = 0
        k = s
        for i in range(len(vertex)):
            custo_atual += grafo[k][vertex[i]] #Atualiza custo da rota da permutação analisada
            k = vertex[i]
        custo_atual += grafo[k][s]
        if custo_atual < custo_min:
            vertex2=vertex.copy()
            solucao=np.array([0,vertex2,0])
        custo_min = min(custo_min, custo_atual) #Caso o custo atual seja menor do que o da permutação de custo mínimo, trocar
        #print (iter, ' - Solucao testada: x=  ', [0, vertex, 0],"f(x)= ", custo_atual) #imprimir a solução atual na tela
        
        iter = iter + 1
        if not permutacao(vertex): #Gerar nova permutação para avaliar a solução
            break
    return [custo_min,solucao, iter]


def permutacao(l):
    n = len(l)
    i = n - 2

    while i >= 0 and l[i] > l[i + 1]:
        i -= 1

    if i == -1:
        return False

    j = i + 1
    while j < n and l[j] > l[i]:
        j += 1

    j -= 1

    #Permutando posições e gerando as novas soluções para analisar
    
    l[i], l[j] = l[j], l[i]
    left = i + 1
    right = n - 1

    while left < right:
        l[left], l[right] = l[right], l[left]
        left += 1
        right -= 1
    return True

def retornaMatrizSimestricaAleatoria(tamanho):
    #tamanho=100;

    m=np.zeros( (tamanho, tamanho) )
    for i in range(tamanho):
        for j in range(tamanho):
            if j!=i:
                m[i][j] = random.randint(1,10)
            
            if m[i][j]!=m[j][i]:
                m[j][i]=m[i][j]

    return m
    #print (m)

 #Funções para leitura das instâncias

def ler_dados(filename):
    if filename == 'si535.tsp' or filename == 'si1032.tsp':
        f = open(filename) #abre o arquivo
        line = f.readline()
        while line.find("DIMENSION") == -1: #procura a dimensão para salvar a qtde de cidades
            line = f.readline()
        n = int(line.split()[-1])
        c = np.zeros([n,n])
        i,j = 0,0

        while line.find("EDGE_WEIGHT_SECTION") == -1: #começa a ler os pesos após os textos iniciais
            line = f.readline()
        data = '0'
        while data != "EOF": #Critério para parar de ler os números das linhas 
            line=f.readline() #ler a linha
            for data in line.split(): #faz um split do conteúdo e lê cada número
                if data != 'EOF':
                    c[i,j]=int(data) #atribuições para formar matriz simétrica de pesos
                    c[j,i]=int(data)  #atribuições para formar matriz simétrica de pesos
                j+= 1 #incrementa próxima coluna da matriz de pesos
                if j>=n: #incrementa próxima linhada matriz de pesos
                    i+= 1
                    j=i
    elif filename == 'pa561.tsp':
        f = open(filename) #abre o arquivo
        line = f.readline()
        while line.find("DIMENSION")==-1: #procura a dimensão para salvar a qtde de cidades
            line = f.readline()
        n=int(line.split()[-1])
        c=np.zeros([n,n])
        i=0
        
        while line.find("EDGE_WEIGHT_SECTION")==-1: #começa a ler os pesos após os textos iniciais
            line=f.readline()
        data='0'
        while data!='DISPLAY_DATA_SECTION': #Critério para parar de ler os números das linhas 
            j=0
            line = f.readline() #ler a linha
            for data in line.split(): #faz um split do conteúdo da linha e lê cada número
                if data!='DISPLAY_DATA_SECTION':
                    c[i,j]=int(data)
                    c[j,i]=int(data)
                    j+=1
            i+=1
    else: return('Instância desconhecida')
    
    return c   


def proxvertice(grafo,s, visits): #funcao para buscar a aresta de menor caminho, a partir de um vertice selecionado s
    indice = 0
    menor = 99999999
    n=grafo.shape[0]
    
    for i in range(n):
        if i!= s and i not in visits: #exclui da verificação o vértice atual e os vértices já visitados
            if grafo[i,s]<menor:
                menor = grafo[i,s]
                indice = i
    return indice, menor
    

def vizproximo(grafo,s):
    print("-------------- Construção Gulosa pelo Vizinho mais Próximo ---------------------")
    print('Vértice inicial: ',s)
    ultimo = s
    n=grafo.shape[0]
    vertex=[]
    custo = 0
    for i in range(n): #Gera vetor dos vértices
        if i != s:
            vertex.append(i)
    
    visits = []
    visits.append(s) #marca o primeiro vértice como visitado
    
    for i in range(n-1):
        aux = proxvertice(grafo,s, visits) #indice e distancia do vértice mais próximo de s (ainda não visitado)
        s=aux[0]
        custo = custo+aux[1]
        visits.append(s) #marca o vértice escolhido como visitado
        print ('Próximo vértice: ', s, 'Custo atual: ', custo)
    
    custo = custo+grafo[s,ultimo] #soma o custo para voltar ao inicio
    visits.append(ultimo)

    print('Último vértice: ', ultimo,'Custo total: ', custo)
    
    return visits


    


In [67]:

#grafo = np.array([[0, 10, 15, 20], [10, 0, 35, 25], [15, 35, 0, 30], [20, 25, 30, 0]]) #Matriz Simétrica
#grafo = np.array([[0, 5, 8, 3], [5, 0, 7, 6], [8, 7, 0, 4], [3, 6, 4, 0]]) #Exemplo do Excel
grafo = retornaMatrizSimestricaAleatoria(10)
print (grafo)
v=grafo.shape[1]
s = 0
inicio = timeit.default_timer()

#res = fb(grafo, s); #Chamada da Função - Força Bruta
res=vizproximo(grafo,s)

fim = timeit.default_timer()
print ('Tempo de Execução: %f' % (fim - inicio), ' segundos.')

print("Menor Caminho: ",res)



[[ 0.  9.  2.  4.  5.  6.  3.  7.  7.  5.]
 [ 9.  0.  5.  2.  3.  7.  2.  6.  8.  3.]
 [ 2.  5.  0.  7.  6.  6. 10.  7.  5.  5.]
 [ 4.  2.  7.  0.  1.  1.  6.  5.  7.  3.]
 [ 5.  3.  6.  1.  0.  2.  4.  2.  4.  2.]
 [ 6.  7.  6.  1.  2.  0.  3.  4. 10.  3.]
 [ 3.  2. 10.  6.  4.  3.  0.  1.  9.  8.]
 [ 7.  6.  7.  5.  2.  4.  1.  0.  1.  8.]
 [ 7.  8.  5.  7.  4. 10.  9.  1.  0. 10.]
 [ 5.  3.  5.  3.  2.  3.  8.  8. 10.  0.]]
-------------- Construção Gulosa pelo Vizinho mais Próximo ---------------------
Vértice inicial:  0
Próximo vértice:  2 Custo atual:  2.0
Próximo vértice:  1 Custo atual:  7.0
Próximo vértice:  3 Custo atual:  9.0
Próximo vértice:  4 Custo atual:  10.0
Próximo vértice:  5 Custo atual:  12.0
Próximo vértice:  6 Custo atual:  15.0
Próximo vértice:  7 Custo atual:  16.0
Próximo vértice:  8 Custo atual:  17.0
Próximo vértice:  9 Custo atual:  27.0
Último vértice:  0 Custo total:  32.0
Tempo de Execução: 0.002516  segundos.
Menor Caminho:  [0, 2, 1, 3, 4, 5, 6, 7, 8,

In [11]:
#Heurísticas Computacionais
import random
from datetime import datetime



def avaliarsolucao(grafo, solucao): #função para calcular o custo de uma rota para o PCV
    n=grafo.shape[0]
    f=0
    for i in range (n):
        f=f+grafo[solucao[i],solucao[i+1]]
    return f

def descidarand(grafo, s_ini, itermax): #Descida Randômica, o vizinho é definido pela troca de um par, selecionado aleatoriamente
    s=s_ini
    n=grafo.shape[0]
    iter = 0
    #print('Solução inicial: ', s,' Distância: ', avaliarsolucao(grafo, s))
    #print('Distância Inicial: ', avaliarsolucao(grafo, s))
    while iter < itermax:
        #print(iter)
        #random.seed(datetime.now())
        i=random.randint(1,n-1) #não considera o primeiro e o ultimo
        #random.seed(datetime.now())
        j=random.randint(1,n-1)
        while j==i: #não selecionar mesma posição
            #random.seed(datetime.now())
            j=random.randint(1,n-1)
        #print('i= ', i, 'j= ', j)
        slinha= s.copy()
        aux = slinha[i]
        slinha[i]=slinha[j]
        slinha[j]=aux
        dist1= avaliarsolucao(grafo,s)
        dist2= avaliarsolucao(grafo,slinha)
        #print(dist2)
        if dist2 < dist1: #se a troca melhor a função objetivo, trocar
            s=slinha.copy()
            iter = 0
            print('Aplicando Busca Local (Descida Randômica) - Solução atualizada (distância): ', dist2, 'Vértices trocados: ', s[i],' e ', s[j])
            dist1=dist2
            #print('Solução atualizada: - Nova Distância: ', dist2)
        else:
            slinha=s.copy()
            iter +=1
    return s
                
def descida(grafo, s_ini): #Descida Completa - vizinho: troca contígua
    #são trocadas as posições contíguas
    s=s_ini
    n=grafo.shape[0]
    #iter = 0
    #print('Solução inicial: ', s,' Distância: ', avaliarsolucao(grafo, s))
    #print('Distância Inicial: ', avaliarsolucao(grafo, s))
    i=1
    while i < n-2:
        j=i+1
        #print('i= ', i, 'j= ', j)
        slinha= s.copy()
        aux = slinha[i]
        slinha[i]=slinha[j]
        slinha[j]=aux
        dist1= avaliarsolucao(grafo,s)
        dist2= avaliarsolucao(grafo,slinha)
        #print(dist2)
        if dist2 < dist1: #se a troca melhorar a função objetivo, trocar
            s=slinha.copy()
            dist1=dist2
            print('Aplicando Busca Local (Descida) - Solução atualizada: - Nova Distância: ', dist1, 'Posições trocadas: ', i,' e ', j)
            i=1
            #print('Solução atualizada: ', s, 'Distância: ', dist2, 'Vértices trocados: ', s[i],' e ', s[j])
                
        else:
            slinha=s.copy()
            i+=1
    return s

def ils(grafo,s_ini, itermax, pert): #Metaherística Iterated Local Seach - itermax (Critério da Busca Local), pert (número máx. de perturbações)
       
        n=grafo.shape[0]
        s=0
        
        #Busca Local
        #x=descida(grafo, s_ini)
        x=descidarand(grafo,s_ini, itermax)
        dist1=avaliarsolucao(grafo,x)
        
        k=1
        while k <= pert:
        #for k in range(pert):
            #criar vetor de trocas
            print("Perturbação: ", k, "pares trocados")
            trocas=[] #vetor de trocas inicial nulo
            m=1
            while m <= 2*k: #montar vetor com os indices para efetuar as trocas de acordo com o nível da perturbação
                #random.seed(datetime.now())
                trocas.append(random.randint(1,n-1))
                #print('trocas: ', trocas, 'm: ', m)
                while m>1 and trocas[m-1] in trocas[0:m-2]: #retirar vértices já escolhidos
                    #random.seed(datetime.now())
                    trocas[m-1]=random.randint(1,n-1)
                m=m+1
            x2=x.copy()
            print('Trocas: ', trocas)
            for i in range(m-2): #realização das trocas (perturbação)
                #print('i: ', i, trocas[i])
                aux=x2[trocas[i]]
                x2[trocas[i]]=x2[trocas[i+1]]
                x2[trocas[i+1]]=aux
            #xlinha= descida(grafo, x2) #Fazer a busca local na solução perturbada
            xlinha=descidarand(grafo,s_ini, itermax)
            dist2=avaliarsolucao(grafo,xlinha)
            print('Busca Local na Solução Perturbada: ', dist2,'- Ótimo até o momento: ', dist1)
            if dist2<dist1:
                x=xlinha.copy()
                dist1=dist2
                print('Solução atualizada: - Nova Distância após perturbação', dist1)
                k=1
            else: 
                k+=1
        
        print('Solução Final pelo ILS: ', dist1)
        
        return dist1
    


In [14]:
#grafo = np.array([[0, 10, 15, 20], [10, 0, 35, 25], [15, 35, 0, 30], [20, 25, 30, 0]]) #Matriz Simétrica
#grafo = np.array([[0, 5, 8, 3], [5, 0, 7, 6], [8, 7, 0, 4], [3, 6, 4, 0]]) #Exemplo do Excel
#grafo = retornaMatrizSimestricaAleatoria(15)
grafo=ler_dados('si1032.tsp')
s=0

#print(grafo)
#np.min(grafo[:,1:s-1],grafo[:,s+1:n])
#np.min(grafo[s+1:n,s])
#np.argmin(grafo[s+1:n,s])
inicio = timeit.default_timer()
s_ini=vizproximo(grafo,s);
#fim = timeit.default_timer()
#print('Tempo de Execução Solução Inicial: %f' % (fim - inicio))
#sol=descidarand(grafo, s_ini, 10000)
#sol=descida(grafo, s_ini)
inicio = timeit.default_timer()
sol=ils(grafo,s_ini, 1000, 20)
fim = timeit.default_timer()
print('Tempo de Execução Solução ILS: %f' % (fim - inicio))
print(sol)

-------------- Construção Gulosa pelo Vizinho mais Próximo ---------------------
Vértice inicial:  0
Próximo vértice:  1 Custo atual:  86.0
Próximo vértice:  2 Custo atual:  172.0
Próximo vértice:  72 Custo atual:  258.0
Próximo vértice:  73 Custo atual:  344.0
Próximo vértice:  74 Custo atual:  430.0
Próximo vértice:  144 Custo atual:  516.0
Próximo vértice:  145 Custo atual:  602.0
Próximo vértice:  146 Custo atual:  688.0
Próximo vértice:  147 Custo atual:  774.0
Próximo vértice:  240 Custo atual:  860.0
Próximo vértice:  241 Custo atual:  946.0
Próximo vértice:  242 Custo atual:  1032.0
Próximo vértice:  243 Custo atual:  1118.0
Próximo vértice:  336 Custo atual:  1204.0
Próximo vértice:  337 Custo atual:  1290.0
Próximo vértice:  338 Custo atual:  1376.0
Próximo vértice:  423 Custo atual:  1451.0
Próximo vértice:  451 Custo atual:  1537.0
Próximo vértice:  461 Custo atual:  1623.0
Próximo vértice:  480 Custo atual:  1709.0
Próximo vértice:  526 Custo atual:  1795.0
Próximo vértice

In [25]:
cidades=13
grafo = retornaMatrizSimestricaAleatoria(cidades)

#print (grafo)
#v=grafo2.shape[1]
s = 0

#------------------------------Modificar para fazer os outros Testes ------------------------------
v=grafo.shape[1]
inicio = timeit.default_timer()
res = fb(grafo, s); #Chamada da Função - Força Bruta
fim = timeit.default_timer()
print (cidades, ' cidades: Menor Distância= ', res[0], 'Solução= ',res[1], ' - Tempo de Execução: %f' % (fim - inicio), ' segundos. # de soluções testadas: ', res[2])
print ('-----------------------------------------------------------------------------------------')
#print("Menor Caminho: ",res)

<ipython-input-11-3e0db4a895c1>:33: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  solucao=np.array([0,vertex2,0])


KeyboardInterrupt: 